// src/components/DemoPage.tsx
import { useState } from 'react';
import HelloTab from './HelloTab';
import HashTab from './HashTab';
import BubbleTab from './BubbleTab';
import ReportPanel from './ReportPanel';
import * as client from '../api/client';
import type { TabKey } from '../types';

const tabs: { key: TabKey; label: string }[] = [
  { key: 'hello', label: 'HelloWorld' },
  { key: 'hash', label: '哈希算法' },
  { key: 'bubble', label: '冒泡排序' }
];

export default function DemoPage() {
  const [activeTab, setActiveTab] = useState<TabKey>('hello');

  const handleExport = async (format: string) => {
    const blob = await client.exportData(activeTab, format);
    const url = window.URL.createObjectURL(new Blob([blob]));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `demo-export.${format === 'excel' ? 'xlsx' : 'csv'}`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: 24 }}>
      <h1>Demo Tools</h1>
      <div>
        {tabs.map(tab => (
          <button key={tab.key} onClick={() => setActiveTab(tab.key)}>
            {tab.label}
          </button>
        ))}
        <button onClick={() => handleExport('csv')}>导出 CSV</button>
        <button onClick={() => handleExport('excel')}>导出 Excel</button>
      </div>
      <div style={{ marginTop: 16 }}>
        {activeTab === 'hello' && <HelloTab />}
        {activeTab === 'hash' && <HashTab />}
        {activeTab === 'bubble' && <BubbleTab />}
      </div>
      <ReportPanel />
    </div>
  );
}

// src/components/DemoPage.vue
<template>
  <div class="demo-page">
    <h1>三接口演示平台</h1>
    <el-tabs v-model="activeTab" type="border-card">
      <el-tab-pane label="Hello World" name="hello">
        <HelloPanel ref="helloRef" />
      </el-tab-pane>
      <el-tab-pane label="SHA-256 哈希" name="hash">
        <HashPanel ref="hashRef" />
      </el-tab-pane>
      <el-tab-pane label="冒泡排序" name="sort">
        <SortPanel ref="sortRef" />
      </el-tab-pane>
    </el-tabs>
    <div class="export-bar">
      <el-button type="success" @click="handleExport" :loading="exportLoading">
        导出当前 Tab 结果 (Excel)
      </el-button>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { exportData } from '../api/index.js'
import { ElMessage } from 'element-plus'
import HelloPanel from './HelloPanel.vue'
import HashPanel from './HashPanel.vue'
import SortPanel from './SortPanel.vue'

const activeTab = ref('hello')
const exportLoading = ref(false)

async function handleExport() {
  exportLoading.value = true
  try {
    const typeMap = { hello: 'hello', hash: 'hash', sort: 'sort' }
    const type = typeMap[activeTab.value] || 'hello'
    const res = await exportData(type)
    // 创建下载链接
    const url = window.URL.createObjectURL(new Blob([res.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', type + '_result.xlsx')
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
    ElMessage.success('导出成功')
  } catch (e) {
    ElMessage.error('导出失败: ' + e.message)
  } finally {
    exportLoading.value = false
  }
}
</script>

<style scoped>
.demo-page { padding: 20px; }
h1 { text-align: center; margin-bottom: 30px; color: #303133; }
.export-bar { margin-top: 20px; text-align: right; }
</style>
