// src/components/HashTab.vue
<template>
  <div class="tab-content">
    <div class="tab-controls">
      <el-input v-model="inputText" placeholder="输入要哈希的字符串" style="width: 300px; margin-right: 12px;" />
      <el-select v-model="algorithm" style="width: 150px; margin-right: 12px;">
        <el-option label="SHA-256" value="SHA-256" />
        <el-option label="MD5" value="MD5" />
        <el-option label="SHA-512" value="SHA-512" />
        <el-option label="SHA-1" value="SHA-1" />
      </el-select>
      <el-button type="primary" @click="callHash" :loading="loading">
        计算哈希
      </el-button>
    </div>
    <div v-if="result" class="result-panel">
      <h4>执行结果：</h4>
      <pre>{{ JSON.stringify(result, null, 2) }}</pre>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { hashApi } from '../api/index.js'
import { ElMessage } from 'element-plus'

const inputText = ref('Hello World')
const algorithm = ref('SHA-256')
const loading = ref(false)
const result = ref(null)

async function callHash() {
  if (!inputText.value) {
    ElMessage.warning('请输入字符串')
    return
  }
  loading.value = true
  try {
    const res = await hashApi.call(inputText.value, algorithm.value)
    result.value = res.data
  } catch (e) {
    ElMessage.error('调用失败: ' + (e.response?.data?.error || e.message))
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.tab-content { padding: 16px; }
.tab-controls {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
  flex-wrap: wrap;
  gap: 8px;
}
.result-panel {
  background: #f5f7fa;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  padding: 16px;
}
.result-panel pre {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-all;
}
</style>

// src/components/HashTab.jsx
import React, { useState } from 'react';
import { computeHash } from '../services/api';
import ExportButton from './ExportButton';

const ALGORITHMS = ['MD5', 'SHA-1', 'SHA-256'];

export default function HashTab() {
    const [input, setInput] = useState('Hello World');
    const [algorithm, setAlgorithm] = useState('SHA-256');
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);

    const handleCompute = async () => {
        setLoading(true);
        try {
            const data = await computeHash(input, algorithm);
            setResult(data);
        } catch (e) {
            setResult({ error: e.message });
        } finally {
            setLoading(false);
        }
    };

    return (
        <div style={{ padding: 16 }}>
            <div style={{ marginBottom: 12 }}>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 'bold' }}>输入文本</label>
                <input type="text" value={input} onChange={e => setInput(e.target.value)}
                       style={inputStyle} />
            </div>
            <div style={{ marginBottom: 12 }}>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 'bold' }}>算法</label>
                <select value={algorithm} onChange={e => setAlgorithm(e.target.value)}
                        style={inputStyle}>
                    {ALGORITHMS.map(a => <option key={a} value={a}>{a}</option>)}
                </select>
            </div>
            <button onClick={handleCompute} disabled={loading} style={btnStyle}>
                {loading ? '计算中...' : '计算哈希'}
            </button>
            <ExportButton tab="hash" />
            {result && (
                <pre style={preStyle}>{JSON.stringify(result, null, 2)}</pre>
            )}
        </div>
    );
}

const btnStyle = {
    padding: '8px 16px', marginRight: 12, cursor: 'pointer',
    background: '#1677ff', color: '#fff', border: 'none', borderRadius: 6,
};
const inputStyle = {
    width: '100%', padding: '8px 12px', border: '1px solid #d9d9d9',
    borderRadius: 6, fontSize: 14,
};
const preStyle = {
    marginTop: 16, padding: 16, background: '#f5f5f5',
    borderRadius: 8, overflow: 'auto',
};
